controller_list:
  - name: fake_Index_controller
    joints:
      - hand
      - hand_to_index_proximal
      - index_proximal_to_index_intermediate
      - index_intermediate_to_index_distal
  - name: fake_Middle_controller
    joints:
      - hand
      - hand_to_middle_proximal
      - middle_proximal_to_middle_intermediate
      - middle_intermediate_to_middle_distal
  - name: fake_RIng_controller
    joints:
      - hand
      - hand_to_ring_proximal
      - ring_proximal_to_ring_intermediate
      - ring_intermediate_to_ring_distal
  - name: fake_Pinky_controller
    joints:
      - hand
      - hand_to_pinky_proximal
      - pinky_proximal_to_pinky_intermediate
      - pinky_intermediate_to_pinky_distal
  - name: fake_Thumb_controller
    joints:
      - hand
      - hand_to_thumb_proximal
      - thumb_proximal_to_thumb_distal
initial:  # Define initial robot poses.
  - group: Index
    pose: Index_pose
  - group: Middle
    pose: Middle_pose
  - group: RIng
    pose: Ring
  - group: Pinky
    pose: Pinky
  - group: Thumb
    pose: Thumb